In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
files = os.listdir(
    "/content/drive/MyDrive/Colab Notebooks/output/statistics"
)
files

['sampled_all_systems.csv',
 'mistral.csv',
 'concat_flaml.csv',
 'llama.csv',
 'concat_ag.csv',
 'concat_rf.csv',
 'hpo_all_systems.csv',
 'result_equal_monotonic_rf_equal.csv',
 'result_monotonic_rf_equal.csv',
 'result_equal_monotonic_flaml_equal.csv',
 'result_monotonic_flaml_equal.csv',
 'result_equal_monotonic_ag_equal.csv',
 'result_monotonic_ag_equal.csv',
 'result_monotonic_llama.csv']

## Mistral

In [4]:
system = "mistral"

In [5]:
df = pd.read_csv(
    f"/content/drive/MyDrive/Colab Notebooks/output/statistics/{system}.csv",
    sep=";"
)
df

,predicted_dataset,selected_llm,number_of_examples,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
0,ed_01,MISTRAL_NEMO_INSTRUCT_2407,0,set(),"{'neutral', 'sarcasm'}",False,0.307054,0.481328,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['sadness', 'sarcasm', 'joy', 'surprise', 'fea..."
1,ed_01,MISTRAL_NEMO_INSTRUCT_2407,5,set(),set(),False,0.307054,0.543568,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['sadness', 'joy', 'surprise', 'fear', 'disgus..."
2,ed_02,MISTRAL_NEMO_INSTRUCT_2407,5,set(),"{'fatigue', 'supportive', 'unsure', 'restlessn...",False,0.342871,0.577312,"['sadness', 'joy', 'surprise', 'fear', 'love',...","['fatigue', 'supportive', 'unsure', 'restlessn..."
3,ed_02,MISTRAL_NEMO_INSTRUCT_2407,0,set(),"{'pain', 'angry', 'b', 'shy', 'calm', 'envy', ...",False,0.342871,0.602581,"['sadness', 'joy', 'surprise', 'fear', 'love',...","['pain', 'sadness', 'angry', 'b', 'shy', 'calm..."
4,ed_03,MISTRAL_NEMO_INSTRUCT_2407,5,set(),"{'pain', 'fatigue', 'gratuity', 'determination...",False,0.294867,0.213996,"['sadness', 'embarrassment', 'excitement', 'an...","['fatigue', 'excitement', 'grateitude', 'self-..."
...,...,...,...,...,...,...,...,...,...,...
91,ua_04,MISTRAL_NEMO_INSTRUCT_2407,5,set(),"{'complicated', 'pointy', 'tiny', 'sound', '2'...",False,0.200040,0.271154,"['3', '5', '10', '1', '7']","['complicated', 'pointy', 'tiny', 'sound', '2'..."
92,ua_05,MISTRAL_NEMO_INSTRUCT_2407,0,set(),set(),False,0.776119,0.129353,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
93,ua_05,MISTRAL_NEMO_INSTRUCT_2407,5,set(),set(),False,0.776119,0.124378,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
94,ua_06,MISTRAL_NEMO_INSTRUCT_2407,5,set(),"{'---', '4', 'good'}",False,0.442095,0.128985,"['3', '5', '10', '1', '7']","['3', '---', '4', '5', '10', '1', 'good', '7']"
95,ua_06,MISTRAL_NEMO_INSTRUCT_2407,0,set(),set(),False,0.442095,0.394275,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"

In [6]:
# Looking at one dataset example
df.query("predicted_dataset == 'ua_01'")

,predicted_dataset,selected_llm,number_of_examples,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
84,ua_01,MISTRAL_NEMO_INSTRUCT_2407,0,set(),"{'---', 'nan'}",False,0.55838,0.245959,"['3', '5', '10', '1', '7']","['3', '---', '5', 'nan', '10', '1', '7']"
85,ua_01,MISTRAL_NEMO_INSTRUCT_2407,5,set(),"{'---', '4', 'nan', 'd', '2', 'deleted', '0'}",False,0.55838,0.324316,"['3', '5', '10', '1', '7']","['3', '---', '4', '5', 'nan', '2', 'd', '10', ..."

In [7]:
grouped_df = (
    df.groupby(
        [
            "predicted_dataset",
            "selected_llm",
        ]
    )
    .agg(
        {
            "hold_out_f1_score": "mean"
        }
    )
)
grouped_df = grouped_df.reset_index()
grouped_df

   predicted_dataset                selected_llm  hold_out_f1_score
0              ed_01  MISTRAL_NEMO_INSTRUCT_2407           0.512448
1              ed_02  MISTRAL_NEMO_INSTRUCT_2407           0.589946
2              ed_03  MISTRAL_NEMO_INSTRUCT_2407           0.247046
3              ed_04  MISTRAL_NEMO_INSTRUCT_2407           0.245070
4              ed_05  MISTRAL_NEMO_INSTRUCT_2407           0.391667
5              fn_01  MISTRAL_NEMO_INSTRUCT_2407           0.238605
6              fn_02  MISTRAL_NEMO_INSTRUCT_2407           0.569444
7              fn_03  MISTRAL_NEMO_INSTRUCT_2407           0.231606
8              fn_04  MISTRAL_NEMO_INSTRUCT_2407           0.264744
9              fn_05  MISTRAL_NEMO_INSTRUCT_2407           0.385104
10             fn_06  MISTRAL_NEMO_INSTRUCT_2407           0.472574
11             fn_07  MISTRAL_NEMO_INSTRUCT_2407           0.389205
12             fn_08  MISTRAL_NEMO_INSTRUCT_2407           0.673483
13             fn_09  MISTRAL_NEMO_INSTRUCT_2407           0.393546
14             fn_10  MISTRAL_NEMO_INSTRUCT_2407           0.391667
15             hs_01  MISTRAL_NEMO_INSTRUCT_2407           0.672676
16             hs_02  MISTRAL_NEMO_INSTRUCT_2407           0.830903
17             hs_03  MISTRAL_NEMO_INSTRUCT_2407           0.834034
18             hs_04  MISTRAL_NEMO_INSTRUCT_2407           0.588340
19             hs_05  MISTRAL_NEMO_INSTRUCT_2407           0.644040
20             hs_06  MISTRAL_NEMO_INSTRUCT_2407           0.610439
21             hs_07  MISTRAL_NEMO_INSTRUCT_2407           0.455778
22             hs_08  MISTRAL_NEMO_INSTRUCT_2407           0.897108
23             hs_09  MISTRAL_NEMO_INSTRUCT_2407           0.747173
24             hs_10  MISTRAL_NEMO_INSTRUCT_2407           0.816667
25             hs_11  MISTRAL_NEMO_INSTRUCT_2407           0.901760
26             hs_12  MISTRAL_NEMO_INSTRUCT_2407           0.581081
27             hs_13  MISTRAL_NEMO_INSTRUCT_2407           0.304910
28             hs_14  MISTRAL_NEMO_INSTRUCT_2407           0.583333
29             hs_15  MISTRAL_NEMO_INSTRUCT_2407           0.596321
30             pc_01  MISTRAL_NEMO_INSTRUCT_2407           0.845300
31             pc_02  MISTRAL_NEMO_INSTRUCT_2407           0.937677
32             pc_03  MISTRAL_NEMO_INSTRUCT_2407           0.697570
33             pc_04  MISTRAL_NEMO_INSTRUCT_2407           0.911145
34             pc_05  MISTRAL_NEMO_INSTRUCT_2407           0.614547
35             pc_06  MISTRAL_NEMO_INSTRUCT_2407           0.894689
36             pc_07  MISTRAL_NEMO_INSTRUCT_2407           0.848765
37             pc_08  MISTRAL_NEMO_INSTRUCT_2407           0.221229
38             pc_09  MISTRAL_NEMO_INSTRUCT_2407           0.757212
39             sd_01  MISTRAL_NEMO_INSTRUCT_2407           0.593750
40             sd_03  MISTRAL_NEMO_INSTRUCT_2407           0.520000
41             sd_04  MISTRAL_NEMO_INSTRUCT_2407           0.522667
42             ua_01  MISTRAL_NEMO_INSTRUCT_2407           0.285138
43             ua_02  MISTRAL_NEMO_INSTRUCT_2407           0.167483
44             ua_03  MISTRAL_NEMO_INSTRUCT_2407           0.173171
45             ua_04  MISTRAL_NEMO_INSTRUCT_2407           0.335317
46             ua_05  MISTRAL_NEMO_INSTRUCT_2407           0.126866
47             ua_06  MISTRAL_NEMO_INSTRUCT_2407           0.261630

### Result

In [8]:
monotonic = (
    df.sort_values(
        [
            "predicted_dataset",
            "selected_llm",
            "number_of_examples",
        ]
    )
    .groupby(
        [
            "predicted_dataset",
            "selected_llm",
        ],
        as_index=False,
        observed=True
    )
    ["hold_out_f1_score"]
    .apply(lambda x: x.is_monotonic_increasing)
    .rename(columns={"hold_out_f1_score": "is_monotonic_increasing"})
    [["predicted_dataset", "selected_llm", "is_monotonic_increasing"]]
)
result = (
    monotonic.merge(
        df,
        on=["predicted_dataset", "selected_llm"],
    )
    .sort_values(["predicted_dataset", "selected_llm"])
)

result.to_csv(
    f"/content/drive/MyDrive/Colab Notebooks/output/statistics/result_monotonic_{system}.csv",
    sep=";"
)
result

,predicted_dataset,selected_llm,is_monotonic_increasing,number_of_examples,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
0,ed_01,MISTRAL_NEMO_INSTRUCT_2407,True,0,set(),"{'neutral', 'sarcasm'}",False,0.307054,0.481328,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['sadness', 'sarcasm', 'joy', 'surprise', 'fea..."
1,ed_01,MISTRAL_NEMO_INSTRUCT_2407,True,5,set(),set(),False,0.307054,0.543568,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['sadness', 'joy', 'surprise', 'fear', 'disgus..."
2,ed_02,MISTRAL_NEMO_INSTRUCT_2407,False,5,set(),"{'fatigue', 'supportive', 'unsure', 'restlessn...",False,0.342871,0.577312,"['sadness', 'joy', 'surprise', 'fear', 'love',...","['fatigue', 'supportive', 'unsure', 'restlessn..."
3,ed_02,MISTRAL_NEMO_INSTRUCT_2407,False,0,set(),"{'pain', 'angry', 'b', 'shy', 'calm', 'envy', ...",False,0.342871,0.602581,"['sadness', 'joy', 'surprise', 'fear', 'love',...","['pain', 'sadness', 'angry', 'b', 'shy', 'calm..."
4,ed_03,MISTRAL_NEMO_INSTRUCT_2407,False,5,set(),"{'pain', 'fatigue', 'gratuity', 'determination...",False,0.294867,0.213996,"['sadness', 'embarrassment', 'excitement', 'an...","['fatigue', 'excitement', 'grateitude', 'self-..."
...,...,...,...,...,...,...,...,...,...,...,...
91,ua_04,MISTRAL_NEMO_INSTRUCT_2407,False,5,set(),"{'complicated', 'pointy', 'tiny', 'sound', '2'...",False,0.200040,0.271154,"['3', '5', '10', '1', '7']","['complicated', 'pointy', 'tiny', 'sound', '2'..."
92,ua_05,MISTRAL_NEMO_INSTRUCT_2407,False,0,set(),set(),False,0.776119,0.129353,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
93,ua_05,MISTRAL_NEMO_INSTRUCT_2407,False,5,set(),set(),False,0.776119,0.124378,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
94,ua_06,MISTRAL_NEMO_INSTRUCT_2407,False,5,set(),"{'---', '4', 'good'}",False,0.442095,0.128985,"['3', '5', '10', '1', '7']","['3', '---', '4', '5', '10', '1', 'good', '7']"
95,ua_06,MISTRAL_NEMO_INSTRUCT_2407,False,0,set(),set(),False,0.442095,0.394275,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"

# Analysis Examples

Some examples of interesting analysis below:

## Monotonic Analysis

### Monotonic increasing count

In [9]:
is_monotonic_increasing_equal = result["is_monotonic_increasing"]

monotonic_increasing_equal = result.loc[is_monotonic_increasing_equal]
non_monotonic_increasing_equal = result.loc[~is_monotonic_increasing_equal]

print(f"Number EQUAL Monotonic increasing: {len(monotonic_increasing_equal.drop_duplicates('predicted_dataset'))}")
print(f"{monotonic_increasing_equal['predicted_dataset'].drop_duplicates().to_list()}")

print(f"Number EQUAL Non-monotonic increasing: {len(non_monotonic_increasing_equal.drop_duplicates('predicted_dataset'))}")
print(f"{non_monotonic_increasing_equal['predicted_dataset'].drop_duplicates().to_list()}")

Number EQUAL Monotonic increasing: 24
['ed_01', 'fn_02', 'fn_03', 'fn_04', 'fn_05', 'fn_06', 'fn_08', 'fn_09', 'fn_10', 'hs_01', 'hs_02', 'hs_05', 'hs_06', 'hs_07', 'hs_10', 'hs_11', 'hs_13', 'hs_15', 'pc_09', 'sd_01', 'sd_03', 'sd_04', 'ua_01', 'ua_02']
Number EQUAL Non-monotonic increasing: 24
['ed_02', 'ed_03', 'ed_04', 'ed_05', 'fn_01', 'fn_07', 'hs_03', 'hs_04', 'hs_08', 'hs_09', 'hs_12', 'hs_14', 'pc_01', 'pc_02', 'pc_03', 'pc_04', 'pc_05', 'pc_06', 'pc_07', 'pc_08', 'ua_03', 'ua_04', 'ua_05', 'ua_06']

### 0 and 5 hold_out_f1_score difference

In [10]:
da_analysis = (
    result.query("number_of_examples == 0")
    .merge(
        result.query("number_of_examples == 5"),
        on=["selected_llm", "predicted_dataset"],
        suffixes=["_0", "_5"]
    )
)
da_analysis["diff"] = da_analysis["hold_out_f1_score_5"] - da_analysis["hold_out_f1_score_0"]

(
    da_analysis
    .sort_values(
        "predicted_dataset",
        ignore_index=True
    )
    [
        [
            "predicted_dataset",
            "selected_llm",
            "number_of_examples_0",
            "number_of_examples_5",
            "is_monotonic_increasing_0",
            "hold_out_f1_score_0",
            "hold_out_f1_score_5",
            "diff"
        ]
    ]
)

,predicted_dataset,selected_llm,number_of_examples_0,number_of_examples_5,is_monotonic_increasing_0,hold_out_f1_score_0,hold_out_f1_score_5,diff
0,ed_01,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.481328,0.543568,0.062241
1,ed_02,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.602581,0.577312,-0.025269
2,ed_03,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.280096,0.213996,-0.066100
3,ed_04,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.297598,0.192542,-0.105056
4,ed_05,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.400000,0.383333,-0.016667
5,fn_01,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.241138,0.236073,-0.005064
6,fn_02,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.569444,0.569444,0.000000
7,fn_03,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.219582,0.243630,0.024048
8,fn_04,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.250328,0.279161,0.028834
9,fn_05,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.373239,0.396969,0.023729
10,fn_06,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.472574,0.472574,0.000000
11,fn_07,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.397727,0.380682,-0.017045
12,fn_08,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.641161,0.705805,0.064644
13,fn_09,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.372171,0.414920,0.042749
14,fn_10,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.341667,0.441667,0.100000
15,hs_01,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.621126,0.724225,0.103099
16,hs_02,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.829621,0.832186,0.002565
17,hs_03,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.842437,0.825630,-0.016807
18,hs_04,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.753673,0.423006,-0.330668
19,hs_05,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.592899,0.695180,0.102281
20,hs_06,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.590772,0.630106,0.039334
21,hs_07,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.444575,0.466981,0.022406
22,hs_08,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.899732,0.894484,-0.005248
23,hs_09,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.862682,0.631664,-0.231018
24,hs_10,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.806667,0.826667,0.020000
25,hs_11,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.879765,0.923754,0.043988
26,hs_12,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.594595,0.567568,-0.027027
27,hs_13,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.271318,0.338501,0.067183
28,hs_14,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.684211,0.482456,-0.201754
29,hs_15,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.567843,0.624799,0.056956
30,pc_01,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.854983,0.835616,-0.019367
31,pc_02,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.946176,0.929178,-0.016997
32,pc_03,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.871895,0.523244,-0.348651
33,pc_04,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.932408,0.889881,-0.042526
34,pc_05,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.628664,0.600430,-0.028233
35,pc_06,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.957584,0.831793,-0.125791
36,pc_07,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.849794,0.847737,-0.002058
37,pc_08,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.363831,0.078628,-0.285204
38,pc_09,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.745192,0.769231,0.024038
39,sd_01,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.541667,0.645833,0.104167
40,sd_03,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.466667,0.573333,0.106667
41,sd_04,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.488000,0.557333,0.069333
42,ua_01,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.245959,0.324316,0.078356
43,ua_02,MISTRAL_NEMO_INSTRUCT_2407,0,5,True,0.121450,0.213516,0.092067
44,ua_03,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.219837,0.126504,-0.093333
45,ua_04,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.399480,0.271154,-0.128326
46,ua_05,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.129353,0.124378,-0.004975
47,ua_06,MISTRAL_NEMO_INSTRUCT_2407,0,5,False,0.394275,0.128985,-0.265290