In [19]:
# %%
import os
import re
import pandas as pd
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score

# Llama

In [20]:
llama_output_results_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/statistics/llama.csv", sep=";")
llama_output_results_df

,predicted_dataset,selected_llm,number_of_examples,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
0,ed_01,LLAMA_3_2_3B_INSTRUCT,5,set(),set(),False,0.307054,0.448133,"['sadness', 'fear', 'disgust', 'anger', 'surpr...","['sadness', 'fear', 'disgust', 'anger', 'surpr..."
1,ed_01,LLAMA_3_2_3B_INSTRUCT,0,set(),{'---'},False,0.307054,0.381743,"['sadness', 'fear', 'disgust', 'anger', 'surpr...","['---', 'sadness', 'fear', 'disgust', 'anger',..."
2,ed_02,LLAMA_3_2_3B_INSTRUCT,5,set(),"{'reassurance', 'slutty', 'smug', 'compassion'...",False,0.342871,0.548982,"['love', 'sadness', 'fear', 'anger', 'surprise...","['reassurance', 'slutty', 'smug', 'compassion'..."
3,ed_02,LLAMA_3_2_3B_INSTRUCT,0,set(),"{'happiness', 'nervousness', 'compassion', 'an...",False,0.342871,0.566905,"['love', 'sadness', 'fear', 'anger', 'surprise...","['compassion', 'anxiety', 'frustration', 'disg..."
4,ed_03,LLAMA_3_2_3B_INSTRUCT,0,set(),"{'ambivalence', 'envyness', 'cautiousness', 'd...",False,0.294867,0.199409,"['annoyance', 'caring', 'sadness', 'disapprova...","['annoyance', 'ambivalence', 'caring', 'envyne..."
...,...,...,...,...,...,...,...,...,...,...
91,ua_04,LLAMA_3_2_3B_INSTRUCT,0,set(),"{'---', '2', '4'}",False,0.200040,0.373475,"['7', '10', '3', '5', '1']","['7', '---', '10', '3', '2', '5', '4', '1']"
92,ua_05,LLAMA_3_2_3B_INSTRUCT,5,set(),{'---'},False,0.776119,0.303483,"['7', '10', '3', '5', '1']","['7', '---', '10', '3', '5', '1']"
93,ua_05,LLAMA_3_2_3B_INSTRUCT,0,set(),"{'---', '500'}",False,0.776119,0.141791,"['7', '10', '3', '5', '1']","['7', '---', '10', '500', '3', '5', '1']"
94,ua_06,LLAMA_3_2_3B_INSTRUCT,5,set(),{'4'},False,0.442095,0.397528,"['7', '10', '3', '5', '1']","['7', '10', '3', '5', '4', '1']"
95,ua_06,LLAMA_3_2_3B_INSTRUCT,0,set(),{'---'},False,0.442095,0.405986,"['7', '10', '3', '5', '1']","['7', '---', '10', '3', '5', '1']"

In [21]:
llama_ed_01_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/five_shot/LLAMA_3_2_3B_INSTRUCT_ed_01_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = llama_ed_01_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_ed_01_df["hold_out_y_pred"].to_list()
final_precision_score = precision_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"ed_01: {final_precision_score}")

llama_fn_05_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/five_shot/LLAMA_3_2_3B_INSTRUCT_fn_05_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = llama_fn_05_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_fn_05_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(
    hold_out_y_true_list, hold_out_y_pred_list
)
print(f"fn_05: {final_acc_score}")

llama_hs_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/five_shot/LLAMA_3_2_3B_INSTRUCT_hs_03_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = llama_hs_03_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_hs_03_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"hs_03: {final_f1_score}")

llama_hs_04_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/zero_shot/LLAMA_3_2_3B_INSTRUCT_hs_04_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = llama_hs_04_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_hs_04_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(
    hold_out_y_true_list, hold_out_y_pred_list
)
print(f"hs_04: {final_acc_score}")

llama_hs_07_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/five_shot/LLAMA_3_2_3B_INSTRUCT_hs_07_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = llama_hs_07_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_hs_07_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"hs_07: {final_f1_score}")

llama_hs_14_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/five_shot/LLAMA_3_2_3B_INSTRUCT_hs_14_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = llama_hs_14_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_hs_14_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"hs_14: {final_f1_score}")

llama_pc_02_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/zero_shot/LLAMA_3_2_3B_INSTRUCT_pc_02_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = llama_pc_02_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_pc_02_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_02: {final_acc_score}")

llama_pc_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/zero_shot/LLAMA_3_2_3B_INSTRUCT_pc_03_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = llama_pc_03_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_pc_03_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_03: {final_acc_score}")

llama_pc_06_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/zero_shot/LLAMA_3_2_3B_INSTRUCT_pc_06_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = llama_pc_06_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_pc_06_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_06: {final_acc_score}")

llama_sd_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/five_shot/LLAMA_3_2_3B_INSTRUCT_sd_03_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = llama_sd_03_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_sd_03_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"sd_03: {final_f1_score}")

llama_sd_04_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/llama/five_shot/LLAMA_3_2_3B_INSTRUCT_sd_04_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = llama_sd_04_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = llama_sd_04_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"sd_04: {final_f1_score}")

ed_01: 0.44813278008298757
fn_05: 0.38640538885486836
hs_03: 0.8046218487394958
hs_04: 0.8724887848644431
hs_07: 0.45468445549233233
hs_14: 0.6271929824561403
pc_02: 0.8441926345609065
pc_03: 0.9167741935483871
pc_06: 0.9550954486483624
sd_03: 0.2732739305809776
sd_04: 0.22000341571063683

In [22]:
mistral_output_results_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/statistics/mistral.csv", sep=";")
mistral_output_results_df

,predicted_dataset,selected_llm,number_of_examples,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
0,ed_01,MISTRAL_NEMO_INSTRUCT_2407,0,set(),"{'sarcasm', 'neutral'}",False,0.307054,0.481328,"['sadness', 'fear', 'disgust', 'anger', 'surpr...","['neutral', 'sadness', 'sarcasm', 'fear', 'dis..."
1,ed_01,MISTRAL_NEMO_INSTRUCT_2407,5,set(),set(),False,0.307054,0.543568,"['sadness', 'fear', 'disgust', 'anger', 'surpr...","['sadness', 'fear', 'disgust', 'anger', 'surpr..."
2,ed_02,MISTRAL_NEMO_INSTRUCT_2407,5,set(),"{'hesitation', 'maturity', 'determined', 'reso...",False,0.342871,0.577312,"['love', 'sadness', 'fear', 'anger', 'surprise...","['hesitation', 'maturity', 'determined', 'reso..."
3,ed_02,MISTRAL_NEMO_INSTRUCT_2407,0,set(),"{'sincere', 'jealousy', '---', 'anxiety', 'fru...",False,0.342871,0.602581,"['love', 'sadness', 'fear', 'anger', 'surprise...","['sadness', 'sincere', 'anger', 'joy', 'jealou..."
4,ed_03,MISTRAL_NEMO_INSTRUCT_2407,0,set(),"{'satire', 'courage', 'exhaustion', 'discomfor...",False,0.294867,0.280096,"['annoyance', 'caring', 'sadness', 'disapprova...","['annoyance', 'caring', 'satire', 'courage', '..."
...,...,...,...,...,...,...,...,...,...,...
91,ua_04,MISTRAL_NEMO_INSTRUCT_2407,0,set(),set(),False,0.200040,0.399480,"['7', '10', '3', '5', '1']","['7', '10', '3', '5', '1']"
92,ua_05,MISTRAL_NEMO_INSTRUCT_2407,0,set(),set(),False,0.776119,0.129353,"['7', '10', '3', '5', '1']","['7', '10', '3', '5', '1']"
93,ua_05,MISTRAL_NEMO_INSTRUCT_2407,5,set(),set(),False,0.776119,0.124378,"['7', '10', '3', '5', '1']","['7', '10', '3', '5', '1']"
94,ua_06,MISTRAL_NEMO_INSTRUCT_2407,0,set(),set(),False,0.442095,0.394275,"['7', '10', '3', '5', '1']","['7', '10', '3', '5', '1']"
95,ua_06,MISTRAL_NEMO_INSTRUCT_2407,5,set(),"{'---', 'good', '4'}",False,0.442095,0.128985,"['7', '10', '3', '5', '1']","['7', '---', '10', 'good', '3', '5', '4', '1']"

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Mistral

In [24]:
mistral_ed_01_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/five_shot/MISTRAL_NEMO_INSTRUCT_2407_ed_01_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = mistral_ed_01_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_ed_01_df["hold_out_y_pred"].to_list()
final_precision_score = precision_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"ed_01: {final_precision_score}")

mistral_fn_05_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/five_shot/MISTRAL_NEMO_INSTRUCT_2407_fn_05_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = mistral_fn_05_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_fn_05_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(
    hold_out_y_true_list, hold_out_y_pred_list
)
print(f"fn_05: {final_acc_score}")

mistral_hs_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/zero_shot/MISTRAL_NEMO_INSTRUCT_2407_hs_03_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = mistral_hs_03_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_hs_03_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"hs_03: {final_f1_score}")

mistral_hs_04_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/zero_shot/MISTRAL_NEMO_INSTRUCT_2407_hs_04_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = mistral_hs_04_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_hs_04_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(
    hold_out_y_true_list, hold_out_y_pred_list
)
print(f"hs_04: {final_acc_score}")

mistral_hs_07_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/five_shot/MISTRAL_NEMO_INSTRUCT_2407_hs_07_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = mistral_hs_07_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_hs_07_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"hs_07: {final_f1_score}")

mistral_hs_14_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/zero_shot/MISTRAL_NEMO_INSTRUCT_2407_hs_14_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = mistral_hs_14_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_hs_14_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"hs_14: {final_f1_score}")

mistral_pc_02_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/zero_shot/MISTRAL_NEMO_INSTRUCT_2407_pc_02_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = mistral_pc_02_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_pc_02_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_02: {final_acc_score}")

mistral_pc_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/zero_shot/MISTRAL_NEMO_INSTRUCT_2407_pc_03_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = mistral_pc_03_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_pc_03_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_03: {final_acc_score}")

mistral_pc_06_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/zero_shot/MISTRAL_NEMO_INSTRUCT_2407_pc_06_predicted_result_0_shot.csv", sep=";")
hold_out_y_true_list = mistral_pc_06_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_pc_06_df["hold_out_y_pred"].to_list()
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_06: {final_acc_score}")

mistral_sd_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/five_shot/MISTRAL_NEMO_INSTRUCT_2407_sd_03_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = mistral_sd_03_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_sd_03_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"sd_03: {final_f1_score}")

mistral_sd_04_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/mistral/five_shot/MISTRAL_NEMO_INSTRUCT_2407_sd_04_predicted_result_5_shot.csv", sep=";")
hold_out_y_true_list = mistral_sd_04_df["hold_out_y_true"].to_list()
hold_out_y_pred_list = mistral_sd_04_df["hold_out_y_pred"].to_list()
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"sd_04: {final_f1_score}")

ed_01: 0.5435684647302904
fn_05: 0.3969687691365585
hs_03: 0.842436974789916
hs_04: 0.7536733632403615
hs_07: 0.4628910300604797
hs_14: 0.6842105263157895
pc_02: 0.9461756373937678
pc_03: 0.8718951612903226
pc_06: 0.9575842622256348
sd_03: 0.5712056774808197
sd_04: 0.5453786930632988

# FLAML

In [25]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/statistics/concat_flaml.csv", sep=";")
df = df.sort_values(by=["predicted_dataset", "hold_out_f1_score"])
adapt_mask = df["concatenated_dataset"] == df["predicted_dataset"]
aug_mask = df["trained_dataset"] == df["predicted_dataset"]
df = df.loc[(~aug_mask)]
# equal_df = df.loc[adapt_mask & (~aug_mask)]
# diff_df = df.loc[(~adapt_mask) & (~aug_mask)]
# equal_df
df[df["trained_dataset"]=="fn_07"]

,trained_dataset,predicted_dataset,concatenated_dataset,automl_system,method,percentage,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
62,fn_07,fn_05,fn_05,FLAML,gmm_random,50,[],[],False,0.333946,0.414779,"['support', 'refutation', 'insufficient_info']","['refutation', 'support', 'insufficient_info']"
60,fn_07,fn_05,fn_05,FLAML,gmm_random,25,[],[],False,0.333946,0.451215,"['support', 'refutation', 'insufficient_info']","['refutation', 'support', 'insufficient_info']"
64,fn_07,fn_05,fn_05,FLAML,gmm_random,75,[],[],False,0.333946,0.477955,"['support', 'refutation', 'insufficient_info']","['refutation', 'support', 'insufficient_info']"

In [26]:
flaml_ed_01_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_ed_03.csv", sep=";")
flaml_ed_01_df["sampled_dataset"] = flaml_ed_01_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_ed_01_df = flaml_ed_01_df[(flaml_ed_01_df["dataset_compared"]=="ed_01") & (flaml_ed_01_df["sampled_dataset"]=="ed_01") & (flaml_ed_01_df["percentage"]==75)]
hold_out_y_true_list = flaml_ed_01_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_ed_01_df["hold_out_y_pred"].iloc[0].split(",")
final_precision_score = precision_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"ed_01: {final_precision_score}")

flaml_fn_05_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_fn_07.csv", sep=";")
flaml_fn_05_df["sampled_dataset"] = flaml_fn_05_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_fn_05_df = flaml_fn_05_df[(flaml_fn_05_df["dataset_compared"]=="fn_05") & (flaml_fn_05_df["sampled_dataset"]=="fn_05") & (flaml_fn_05_df["percentage"]==75)]
hold_out_y_true_list = flaml_fn_05_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_fn_05_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(
    hold_out_y_true_list, hold_out_y_pred_list
)
print(f"fn_05: {final_acc_score}")

flaml_hs_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_hs_10.csv", sep=";")
flaml_hs_03_df["sampled_dataset"] = flaml_hs_03_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_hs_03_df = flaml_hs_03_df[(flaml_hs_03_df["dataset_compared"]=="hs_03") & (flaml_hs_03_df["sampled_dataset"]=="hs_03") & (flaml_hs_03_df["percentage"]==75)]
hold_out_y_true_list = flaml_hs_03_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_hs_03_df["hold_out_y_pred"].iloc[0].split(",")
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"hs_03: {final_f1_score}")

flaml_hs_04_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_hs_14.csv", sep=";")
flaml_hs_04_df["sampled_dataset"] = flaml_hs_04_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_hs_04_df = flaml_hs_04_df[(flaml_hs_04_df["dataset_compared"]=="hs_04") & (flaml_hs_04_df["sampled_dataset"]=="hs_04") & (flaml_hs_04_df["percentage"]==75)]
hold_out_y_true_list = flaml_hs_04_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_hs_04_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(
    hold_out_y_true_list, hold_out_y_pred_list
)
print(f"hs_04: {final_acc_score}")

flaml_hs_14_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_hs_04.csv", sep=";")
flaml_hs_14_df["sampled_dataset"] = flaml_hs_14_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_hs_14_df = flaml_hs_14_df[(flaml_hs_14_df["dataset_compared"]=="hs_14") & (flaml_hs_14_df["sampled_dataset"]=="hs_14") & (flaml_hs_14_df["percentage"]==75)]
hold_out_y_true_list = flaml_hs_14_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_hs_14_df["hold_out_y_pred"].iloc[0].split(",")
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"hs_14: {final_f1_score}")

flaml_pc_02_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_pc_01.csv", sep=";")
flaml_pc_02_df["sampled_dataset"] = flaml_pc_02_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_pc_02_df = flaml_pc_02_df[(flaml_pc_02_df["dataset_compared"]=="pc_02") & (flaml_pc_02_df["sampled_dataset"]=="pc_02") & (flaml_pc_02_df["percentage"]==50)]
hold_out_y_true_list = flaml_pc_02_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_pc_02_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_02: {final_acc_score}")

flaml_pc_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_pc_04.csv", sep=";")
flaml_pc_03_df["sampled_dataset"] = flaml_pc_03_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_pc_03_df = flaml_pc_03_df[(flaml_pc_03_df["dataset_compared"]=="pc_03") & (flaml_pc_03_df["sampled_dataset"]=="pc_03") & (flaml_pc_03_df["percentage"]==50)]
hold_out_y_true_list = flaml_pc_03_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_pc_03_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_03: {final_acc_score}")

flaml_pc_06_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_pc_09.csv", sep=";")
flaml_pc_06_df["sampled_dataset"] = flaml_pc_06_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_pc_06_df = flaml_pc_06_df[(flaml_pc_06_df["dataset_compared"]=="pc_06") & (flaml_pc_06_df["sampled_dataset"]=="pc_06") & (flaml_pc_06_df["percentage"]==75)]
hold_out_y_true_list = flaml_pc_06_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_pc_06_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_06: {final_acc_score}")

flaml_sd_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_sd_04.csv", sep=";")
flaml_sd_03_df["sampled_dataset"] = flaml_sd_03_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_sd_03_df = flaml_sd_03_df[(flaml_sd_03_df["dataset_compared"]=="sd_03") & (flaml_sd_03_df["sampled_dataset"]=="sd_03") & (flaml_sd_03_df["percentage"]==75)]
hold_out_y_true_list = flaml_sd_03_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_sd_03_df["hold_out_y_pred"].iloc[0].split(",")
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"sd_03: {final_f1_score}")

flaml_sd_04_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_sd_03.csv", sep=";")
flaml_sd_04_df["sampled_dataset"] = flaml_sd_04_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_sd_04_df = flaml_sd_04_df[(flaml_sd_04_df["dataset_compared"]=="sd_04") & (flaml_sd_04_df["sampled_dataset"]=="sd_04") & (flaml_sd_04_df["percentage"]==75)]
hold_out_y_true_list = flaml_sd_04_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = flaml_sd_04_df["hold_out_y_pred"].iloc[0].split(",")
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"sd_04: {final_f1_score}")

ed_01: 0.04564315352697095
fn_05: 0.47795468462951624
hs_03: 0.7605042016806722
hs_04: 0.9247123073922372
hs_14: 0.8947368421052632
pc_02: 0.8045325779036827
pc_03: 0.8553629032258064
pc_06: 0.907649130239085
sd_03: 0.17172044164058362
sd_04: 0.3586629746835443

In [27]:
flaml_fn_05_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/flaml/flaml_100_combination_summary_gmm_random_fn_07.csv", sep=";")
flaml_fn_05_df["sampled_dataset"] = flaml_fn_05_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
flaml_fn_05_df

,duration_training,duration_prediction,automl_system,dataset_compared,trained_dataset,hold_out_f1_score,validation_best_score,validation_all_scores,5_fold_validation_scores,hold_out_y_true,hold_out_y_pred,hold_out_y_pred_proba,name_best_classifier,method,percentage,combination_trained,sampled_dataset
0,0 days 02:38:47.625573,0 days 00:00:01.854118,FLAML,fn_05,fn_07,0.451215,0.400518,"[0.46587964295997697, 0.46156061042326524, 0.4...","[0, 0, 0, 0, 0]","['insufficient_info,support,refutation,support...","['refutation,support,support,support,support,s...","[0, 0, 0, 0, 0]","lgbm {'n_estimators': 53, 'num_leaves': 4, 'mi...",gmm_random,25,base_dataset_fn_07_dataset_sampled_to_concat_f...,fn_05
1,0 days 02:38:47.625573,0 days 00:00:01.247745,FLAML,fn_07,fn_07,0.420455,0.400518,"[0.46587964295997697, 0.46156061042326524, 0.4...","[0, 0, 0, 0, 0]","['insufficient_info,insufficient_info,refutati...","['support,support,support,insufficient_info,su...","[0, 0, 0, 0, 0]","lgbm {'n_estimators': 53, 'num_leaves': 4, 'mi...",gmm_random,25,base_dataset_fn_07_dataset_sampled_to_concat_f...,fn_05
2,0 days 02:02:24.694477,0 days 00:00:00.453297,FLAML,fn_05,fn_07,0.414779,0.403877,"[0.46363503862410727, 0.4594082495263081, 0.45...","[0, 0, 0, 0, 0]","['insufficient_info,support,refutation,support...","['refutation,support,support,support,support,s...","[0, 0, 0, 0, 0]","extra_tree {'n_estimators': 56, 'max_features'...",gmm_random,50,base_dataset_fn_07_dataset_sampled_to_concat_f...,fn_05
3,0 days 02:02:24.694477,0 days 00:00:00.140590,FLAML,fn_07,fn_07,0.414773,0.403877,"[0.46363503862410727, 0.4594082495263081, 0.45...","[0, 0, 0, 0, 0]","['insufficient_info,insufficient_info,refutati...","['support,support,support,support,support,refu...","[0, 0, 0, 0, 0]","extra_tree {'n_estimators': 56, 'max_features'...",gmm_random,50,base_dataset_fn_07_dataset_sampled_to_concat_f...,fn_05
4,0 days 05:42:46.172360,0 days 00:00:02.065625,FLAML,fn_05,fn_07,0.477955,0.405933,"[0.4620413739266198, 0.4564793130366901, 0.452...","[0, 0, 0, 0, 0]","['insufficient_info,support,refutation,support...","['refutation,support,support,support,support,s...","[0, 0, 0, 0, 0]","lgbm {'n_estimators': 43, 'num_leaves': 20, 'm...",gmm_random,75,base_dataset_fn_07_dataset_sampled_to_concat_f...,fn_05
5,0 days 05:42:46.172360,0 days 00:00:01.124925,FLAML,fn_07,fn_07,0.423295,0.405933,"[0.4620413739266198, 0.4564793130366901, 0.452...","[0, 0, 0, 0, 0]","['insufficient_info,insufficient_info,refutati...","['support,support,support,support,support,refu...","[0, 0, 0, 0, 0]","lgbm {'n_estimators': 43, 'num_leaves': 20, 'm...",gmm_random,75,base_dataset_fn_07_dataset_sampled_to_concat_f...,fn_05

# AutoGluon

In [28]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/statistics/concat_ag.csv", sep=";")
df = df.sort_values(by=["predicted_dataset", "hold_out_f1_score"])
adapt_mask = df["concatenated_dataset"] == df["predicted_dataset"]
aug_mask = df["trained_dataset"] == df["predicted_dataset"]
df = df.loc[(~aug_mask)]
df

,trained_dataset,predicted_dataset,concatenated_dataset,automl_system,method,percentage,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
9,ed_03,ed_01,ed_02,AutoGluon,gmm_random,25,"['surprise', 'fear', 'disgust', 'sadness']","['curiosity', 'admiration', 'neutral']",False,0.307054,0.012448,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['curiosity', 'admiration', 'joy', 'neutral', ..."
12,ed_03,ed_01,ed_02,AutoGluon,gmm_random,50,"['surprise', 'fear', 'disgust']","['relief', 'nervousness', 'admiration', 'curio...",False,0.307054,0.020747,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['relief', 'nervousness', 'admiration', 'curio..."
15,ed_03,ed_01,ed_02,AutoGluon,gmm_random,75,"['surprise', 'fear', 'disgust']","['curiosity', 'admiration', 'neutral', 'optimi...",False,0.307054,0.037344,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['curiosity', 'admiration', 'sadness', 'joy', ..."
0,ed_03,ed_01,ed_01,AutoGluon,gmm_random,25,"['surprise', 'disgust', 'anger']","['admiration', 'disappointment', 'neutral', 'g...",False,0.307054,0.132780,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['admiration', 'sadness', 'joy', 'disappointme..."
6,ed_03,ed_01,ed_01,AutoGluon,gmm_random,75,[],"['neutral', 'admiration', 'remorse']",False,0.307054,0.294606,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['admiration', 'sadness', 'joy', 'surprise', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1854,ua_03,ua_06,ua_06,AutoGluon,gmm_random,50,[],[],False,0.442095,0.585556,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1793,ua_02,ua_06,ua_06,AutoGluon,gmm_random,50,[],[],False,0.442095,0.585882,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1849,ua_03,ua_06,ua_06,AutoGluon,gmm_random,25,[],[],False,0.442095,0.587508,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1859,ua_03,ua_06,ua_06,AutoGluon,gmm_random,75,[],[],False,0.442095,0.598406,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1799,ua_02,ua_06,ua_06,AutoGluon,gmm_random,75,[],[],False,0.442095,0.598731,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"

In [29]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_ed_03.csv", sep=";")
df["sampled_dataset"] = df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
df = df[(df["dataset_compared"]=="ed_01") & (df["sampled_dataset"]=="ed_01") & (df["percentage"]==50)]
df

,duration_training,duration_prediction,automl_system,dataset_compared,trained_dataset,hold_out_f1_score,validation_best_score,validation_all_scores,5_fold_validation_scores,hold_out_y_true,hold_out_y_pred,hold_out_y_pred_proba,name_best_classifier,method,percentage,combination_trained,sampled_dataset
3,0 days 14:20:33.074467,0 days 00:00:02.538081,AutoGluon,ed_01,ed_03,0.302905,0.462602,0.462602,"[0, 0, 0, 0, 0]","anger,joy,sadness,surprise,sadness,surprise,an...","surprise,neutral,neutral,surprise,neutral,sadn...","[0, 0, 0, 0, 0]",WeightedEnsemble_L2 {'ensemble_size': 47} {'us...,gmm_random,50,base_dataset_ed_03_dataset_sampled_to_concat_e...,ed_01

In [30]:
ag_ed_01_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_ed_03.csv", sep=";")
ag_ed_01_df["sampled_dataset"] = ag_ed_01_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_ed_01_df = ag_ed_01_df[(ag_ed_01_df["dataset_compared"]=="ed_01") & (ag_ed_01_df["sampled_dataset"]=="ed_01") & (ag_ed_01_df["percentage"]==50)]
hold_out_y_true_list = ag_ed_01_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_ed_01_df["hold_out_y_pred"].iloc[0].split(",")
final_precision_score = precision_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"ed_01: {final_precision_score}")

ag_fn_05_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_fn_07.csv", sep=";")
ag_fn_05_df["sampled_dataset"] = ag_fn_05_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_fn_05_df = ag_fn_05_df[(ag_fn_05_df["dataset_compared"]=="fn_05") & (ag_fn_05_df["sampled_dataset"]=="fn_05") & (ag_fn_05_df["percentage"]==25)]
hold_out_y_true_list = ag_fn_05_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_fn_05_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(
    hold_out_y_true_list, hold_out_y_pred_list
)
print(f"fn_05: {final_acc_score}")

ag_hs_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_hs_10.csv", sep=";")
ag_hs_03_df["sampled_dataset"] = ag_hs_03_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_hs_03_df = ag_hs_03_df[(ag_hs_03_df["dataset_compared"]=="hs_03") & (ag_hs_03_df["sampled_dataset"]=="hs_03") & (ag_hs_03_df["percentage"]==75)]
hold_out_y_true_list = ag_hs_03_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_hs_03_df["hold_out_y_pred"].iloc[0].split(",")
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"hs_03: {final_f1_score}")

ag_hs_04_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_hs_14.csv", sep=";")
ag_hs_04_df["sampled_dataset"] = ag_hs_04_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_hs_04_df = ag_hs_04_df[(ag_hs_04_df["dataset_compared"]=="hs_04") & (ag_hs_04_df["sampled_dataset"]=="hs_04") & (ag_hs_04_df["percentage"]==75)]
hold_out_y_true_list = ag_hs_04_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_hs_04_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(
    hold_out_y_true_list, hold_out_y_pred_list
)
print(f"hs_04: {final_acc_score}")

ag_hs_14_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_hs_04.csv", sep=";")
ag_hs_14_df["sampled_dataset"] = ag_hs_14_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_hs_14_df = ag_hs_14_df[(ag_hs_14_df["dataset_compared"]=="hs_14") & (ag_hs_14_df["sampled_dataset"]=="hs_14") & (ag_hs_14_df["percentage"]==75)]
hold_out_y_true_list = ag_hs_14_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_hs_14_df["hold_out_y_pred"].iloc[0].split(",")
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="micro"
)
print(f"hs_14: {final_f1_score}")

ag_pc_02_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_pc_04.csv", sep=";")
ag_pc_02_df["sampled_dataset"] = ag_pc_02_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_pc_02_df = ag_pc_02_df[(ag_pc_02_df["dataset_compared"]=="pc_02") & (ag_pc_02_df["sampled_dataset"]=="pc_02") & (ag_pc_02_df["percentage"]==50)]
hold_out_y_true_list = ag_pc_02_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_pc_02_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_02: {final_acc_score}")

ag_pc_02_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_pc_06.csv", sep=";")
ag_pc_02_df["sampled_dataset"] = ag_pc_02_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_pc_02_df = ag_pc_02_df[(ag_pc_02_df["dataset_compared"]=="pc_02") & (ag_pc_02_df["sampled_dataset"]=="pc_04") & (ag_pc_02_df["percentage"]==25)]
hold_out_y_true_list = ag_pc_02_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_pc_02_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_02: {final_acc_score}")

ag_pc_02_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_pc_09.csv", sep=";")
ag_pc_02_df["sampled_dataset"] = ag_pc_02_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_pc_02_df = ag_pc_02_df[(ag_pc_02_df["dataset_compared"]=="pc_02") & (ag_pc_02_df["sampled_dataset"]=="pc_06") & (ag_pc_02_df["percentage"]==50)]
hold_out_y_true_list = ag_pc_02_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_pc_02_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_02: {final_acc_score}")

ag_pc_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_pc_07.csv", sep=";")
ag_pc_03_df["sampled_dataset"] = ag_pc_03_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_pc_03_df = ag_pc_03_df[(ag_pc_03_df["dataset_compared"]=="pc_03") & (ag_pc_03_df["sampled_dataset"]=="pc_03") & (ag_pc_03_df["percentage"]==75)]
hold_out_y_true_list = ag_pc_03_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_pc_03_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_03: {final_acc_score}")

ag_pc_06_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_pc_03.csv", sep=";")
ag_pc_06_df["sampled_dataset"] = ag_pc_06_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_pc_06_df = ag_pc_06_df[(ag_pc_06_df["dataset_compared"]=="pc_06") & (ag_pc_06_df["sampled_dataset"]=="pc_06") & (ag_pc_06_df["percentage"]==75)]
hold_out_y_true_list = ag_pc_06_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_pc_06_df["hold_out_y_pred"].iloc[0].split(",")
final_acc_score = accuracy_score(hold_out_y_true_list, hold_out_y_pred_list)
print(f"pc_06: {final_acc_score}")

ag_sd_03_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_sd_04.csv", sep=";")
ag_sd_03_df["sampled_dataset"] = ag_sd_03_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_sd_03_df = ag_sd_03_df[(ag_sd_03_df["dataset_compared"]=="sd_03") & (ag_sd_03_df["sampled_dataset"]=="sd_03") & (ag_sd_03_df["percentage"]==75)]
hold_out_y_true_list = ag_sd_03_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_sd_03_df["hold_out_y_pred"].iloc[0].split(",")
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"sd_03: {final_f1_score}")

ag_sd_04_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/output/concat/autogluon/autogluon_summary_gmm_random_sd_03.csv", sep=";")
ag_sd_04_df["sampled_dataset"] = ag_sd_04_df["combination_trained"].apply(lambda x: "_".join(x.split("_")[8:10]))
ag_sd_04_df = ag_sd_04_df[(ag_sd_04_df["dataset_compared"]=="sd_04") & (ag_sd_04_df["sampled_dataset"]=="sd_04") & (ag_sd_04_df["percentage"]==75)]
hold_out_y_true_list = ag_sd_04_df["hold_out_y_true"].iloc[0].split(",")
hold_out_y_pred_list = ag_sd_04_df["hold_out_y_pred"].iloc[0].split(",")
final_f1_score = f1_score(
    hold_out_y_true_list, hold_out_y_pred_list, average="macro"
)
print(f"sd_04: {final_f1_score}")

ed_01: 0.3029045643153527
fn_05: 0.5195448050622576
hs_03: 0.7647058823529411
hs_04: 0.9241434237045706
hs_14: 0.7105263157894737
pc_02: 0.8186968838526912
pc_02: 0.8186968838526912
pc_02: 0.8186968838526912
pc_03: 0.8578225806451613
pc_06: 0.9214699886150017
sd_03: 0.2016821121070937
sd_04: 0.40143435676131317